### ISSUE TITLE
Is it possible to use a Zsh alias in a Zsh script?

### ISSUE THREAD

**Issue by mmaayylliiss** [mmaayylliiss/dotfiles#14]
See my `python` script: https://github.com/mmaayylliiss/dotfiles/blob/master/scripts/setup/python

✅ Works
```bash
pip install -r $HOME/Desktop/dotfiles/python/requirements.txt
```

❌ Does not work
(See [`pipinstall` alias](https://github.com/mmaayylliiss/dotfiles/blob/master/zsh/zshrc.symlink#L97))
```bash
pipinstall
```

The output:
```bash
❯ scripts/setup/python
scripts/setup/python:3: command not found: pipinstall
```

@Awea An idea?

**Comment by Awea** [comment]
@mmaayylliiss you can `source $HOME/.zshrc` at the begining of your script
